In [105]:
import os
import sys
sys.path.append(os.path.dirname((os.path.abspath(''))))
import pandas as pd

from src.pipeline import Pipeline
from src.preprocessing.preprocessing import tokenization, removal, stemming

In [132]:
collection = pd.read_csv('../data/TREC_Passage/collection.tsv', sep='\t', names=["pID", "Passage"], header=None)
queries = pd.read_csv('../data/TREC_Passage/queries.dev.tsv', sep='\t', names=["qID", "Query"], header=None)

In [ ]:
#pipeline = Pipeline(collection = '../data/raw/collection.pkl', queries = '../data/raw/queries.pkl')
#pipeline = Pipeline(collection = collection, queries = queries)

In [133]:
collection.Passage

0          The presence of communication amid scientific ...
1          The Manhattan Project and its atomic bomb help...
2          Essay on The Manhattan Project - The Manhattan...
3          The Manhattan Project was the name for a proje...
4          versions of each volume as well as complementa...
                                 ...                        
8841818    When metal salts emit short wavelengths of vis...
8841819    Thousands of people across the United States w...
8841820    The recipe that creates blue, for example, inc...
8841821    On Independence Days of yore, old-timey crowds...
8841822    View full size image. Behind the scenes of the...
Name: Passage, Length: 8841823, dtype: object

In [103]:
queries.head()

qID                           Query
0  1048578  cost of endless pools/swim spa
1  1048579                    what is pcnt
2  1048580               what is pcb waste
3  1048581                   what is pbis?
4  1048582                  what is paysky

In [104]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from tqdm import tqdm
import numpy as np


class TFIDF(object):

    vectorizer = None

    def fit(self, text_in_tokens: pd.Series):
        def dummy(text):
            return text

        self.vectorizer = TfidfVectorizer(tokenizer=dummy, lowercase=False)
        self.vectorizer.fit(text_in_tokens)

        return self

    def transform(self, text_in_tokens: pd.Series):
        assert self.vectorizer is not None, 'You need to fit me first'

        tfidf_matrix = self.vectorizer.transform(text_in_tokens)
        token_names = self.vectorizer.get_feature_names()
        tf_idf_dict = {}
        j = 0

        for name in token_names:
            tf_idf_dict[name] = j
            j += 1

        tf_idf_list = []
        for i in tqdm(range(len(text_in_tokens))):
            tf_idf_token = {}
            for token in text_in_tokens[i]:
                tf_idf_token[token] = tfidf_matrix[i, tf_idf_dict[token]]
            tf_idf_list.append(tf_idf_token)
        tf_idf_vec = np.array(tf_idf_list)

        return tf_idf_vec


In [134]:
x = collection.Passage[:40]
x

0     The presence of communication amid scientific ...
1     The Manhattan Project and its atomic bomb help...
2     Essay on The Manhattan Project - The Manhattan...
3     The Manhattan Project was the name for a proje...
4     versions of each volume as well as complementa...
5     The Manhattan Project. This once classified ph...
6     Nor will it attempt to substitute for the extr...
7     Manhattan Project. The Manhattan Project was a...
8     In June 1942, the United States Army Corps of ...
9     One of the main reasons Hanford was selected a...
10    group discussions, community boards or panels ...
11    punishment designed to repair the damage done ...
12    Tutorial: Introduction to Restorative Justice....
13    Organize volunteer community panels, boards, o...
14    The purpose of this paper is to point out a nu...
15    Each of these types of communities—the geogr...
16    The approach is based on a theory of justice t...
17    Inherent in many people’s understanding 

In [136]:
x = x.progress_apply(lambda text: np.array(
            stemming(
                removal(
                    tokenization(text)
                ))))

100%|██████████| 40/40 [00:00<00:00, 350.57it/s]


In [139]:
#collection['tfidf_embedding'] = tfidf.fit(x).transform(x)
output = tfidf.fit(x).transform(x)

c:\users\d073999\documents\priv-dev\retriever\lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  "The parameter 'token_pattern' will not be used"
c:\users\d073999\documents\priv-dev\retriever\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
100%|██████████| 40/40 [00:00<00:00, 1045.88it/s]

{'presenc': 0.19169979611672686}
{'presenc': 0.19169979611672686, 'commun': 0.11998316454888718}
{'presenc': 0.19169979611672686, 'commun': 0.11998316454888718, 'amid': 0.19169979611672686}
{'presenc': 0.19169979611672686, 'commun': 0.11998316454888718, 'amid': 0.19169979611672686, 'scientif': 0.3833995922334537}
{'presenc': 0.19169979611672686, 'commun': 0.11998316454888718, 'amid': 0.19169979611672686, 'scientif': 0.3833995922334537, 'mind': 0.19169979611672686}
{'presenc': 0.19169979611672686, 'commun': 0.11998316454888718, 'amid': 0.19169979611672686, 'scientif': 0.3833995922334537, 'mind': 0.19169979611672686, 'equal': 0.19169979611672686}
{'presenc': 0.19169979611672686, 'commun': 0.11998316454888718, 'amid': 0.19169979611672686, 'scientif': 0.3833995922334537, 'mind': 0.19169979611672686, 'equal': 0.19169979611672686, 'import': 0.19169979611672686}
{'presenc': 0.19169979611672686, 'commun': 0.11998316454888718, 'amid': 0.19169979611672686, 'scientif': 0.3833995922334537, 'mind':

In [142]:
output

array([{'presenc': 0.19169979611672686, 'commun': 0.11998316454888718, 'amid': 0.19169979611672686, 'scientif': 0.3833995922334537, 'mind': 0.19169979611672686, 'equal': 0.19169979611672686, 'import': 0.19169979611672686, 'success': 0.34473324190582777, 'manhattan': 0.11041488942969002, 'project': 0.11041488942969002, 'intellect': 0.19169979611672686, 'cloud': 0.19169979611672686, 'hang': 0.19169979611672686, 'impress': 0.19169979611672686, 'achiev': 0.19169979611672686, 'atom': 0.12559923363629932, 'research': 0.17236662095291388, 'engin': 0.15864951487651308, 'truli': 0.19169979611672686, 'meant': 0.19169979611672686, 'hundr': 0.19169979611672686, 'thousand': 0.19169979611672686, 'innoc': 0.19169979611672686, 'live': 0.19169979611672686, 'obliter': 0.19169979611672686},
       {'manhattan': 0.15059747631090326, 'project': 0.15059747631090326, 'atom': 0.3426155242270081, 'bomb': 0.17130776211350404, 'help': 0.2614638809458508, 'bring': 0.23509490658210916, 'end': 0.21638582152967742, 

In [ ]:
!pip install "tensorflow>=2.0.0"
!pip install --upgrade tensorflow-hub

In [ ]:
import tensorflow_hub as hub
import tensorflow as tf

elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)

In [ ]:

elmo = elmo_module()

In [ ]:
!pip install allennlp==0.9.0

In [ ]:
!pip install flair

In [98]:
from flair.embeddings import ELMoEmbeddings
from flair.data import Sentence

# init embedding
embedding = ELMoEmbeddings()

In [99]:
# embed words in sentence
# create a sentence
sentence = Sentence('The grass is green .')

# embed words in sentence
embedding.embed(sentence)
for token in sentence:
    print(token)
    print(token.embedding)

Token[0]: "The"
tensor([-0.3288,  0.2022, -0.5940,  ..., -1.2773,  0.3049,  0.2150])
Token[1]: "grass"
tensor([ 0.2539, -0.2363,  0.5263,  ..., -0.7001,  0.8798,  1.4191])
Token[2]: "is"
tensor([ 0.1915,  0.2300, -0.2894,  ..., -0.3626,  1.9066,  1.4520])
Token[3]: "green"
tensor([ 0.1779,  0.1309, -0.1041,  ..., -0.1006,  1.6152,  0.3299])
Token[4]: "."
tensor([-0.8872, -0.2004, -1.0601,  ..., -0.0106, -0.0833,  0.0669])


In [144]:
x = collection.Passage[:100]
#sentence_list = [embedding.embed(Sentence(line)) for line in x]

In [145]:
for line in x:
    sentence = Sentence(line)
    emb = embedding.embed(sentence)
    for token in sentence:
        print(token.embedding)

tensor([-0.3288,  0.2022, -0.5940,  ..., -0.2879,  0.4912,  0.0945])
tensor([-0.4335,  1.0174, -0.7131,  ..., -0.3751,  1.4165, -0.4075])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -1.6505, -0.4502, -0.1458])
tensor([ 0.3358, -0.6698, -0.0683,  ...,  0.5426,  0.2744, -0.2716])
tensor([-5.6628e-01, -2.1065e-02,  2.1309e-06,  ..., -4.3523e-01,
         7.5148e-01, -5.5541e-01])
tensor([-0.3897, -0.5744,  0.1275,  ...,  1.6140,  0.3423, -1.2748])
tensor([-0.4204, -0.1053, -0.7463,  ...,  1.6170,  1.7666, -0.2729])
tensor([ 0.2981, -0.0738, -0.1319,  ...,  0.3481,  0.7208,  0.2200])
tensor([-0.1151, -0.6863, -0.0091,  ...,  0.2669,  0.0373, -1.0258])
tensor([-0.4031, -0.2223, -0.0422,  ..., -0.1549,  0.9292, -1.7620])
tensor([-0.1821,  0.0381,  0.1691,  ...,  0.5510, -0.8244, -1.1586])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.5522, -0.1269, -1.0468])
tensor([-0.5432, -0.2020, -0.1650,  ..., -0.9970,  2.7737, -0.8996])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -1.7679,  0.1539, -1.2161])
te

tensor([-0.3288,  0.2022, -0.5940,  ..., -0.5849,  0.5399, -0.5090])
tensor([-0.1881, -0.2484,  0.5997,  ..., -0.7757,  1.5385, -0.4913])
tensor([ 0.2678, -0.2839, -1.6761,  ..., -0.0675,  1.7258, -0.5118])
tensor([ 0.2981, -0.0738, -0.1319,  ..., -1.3374,  0.3530,  0.1457])
tensor([-0.0690,  0.1126,  0.2371,  ..., -0.7484,  0.0992,  0.2822])
tensor([-0.2674, -0.1357, -0.1691,  ..., -0.1449,  1.6824,  0.4698])
tensor([-0.2415,  0.0541, -0.3114,  ..., -0.1964, -0.2709, -0.3315])
tensor([ 0.1040,  0.1229, -0.0706,  ...,  0.0404,  0.7718, -0.6315])
tensor([ 0.2009, -0.1494, -0.7966,  ..., -0.8937,  1.5359, -0.1754])
tensor([ 0.4359, -0.2371,  0.1499,  ..., -0.6557,  0.5641,  0.1783])
tensor([-0.3088,  0.6863,  0.3279,  ..., -1.4629, -0.0313, -0.7643])
tensor([ 1.1053, -0.1148, -0.2128,  ...,  0.2435,  0.9960, -0.3165])
tensor([-0.2445, -0.7706, -0.9120,  ...,  1.5802, -0.2082, -2.2484])
tensor([ 0.2945, -0.0066,  0.2763,  ...,  0.1552,  0.8685, -1.0772])
tensor([ 0.1131,  0.1575,  0.1414,

tensor([ 0.8518, -0.9071, -1.4499,  ..., -0.1968,  0.1873, -0.5878])
tensor([ 0.3605, -0.1958,  0.0624,  ..., -0.9928,  0.5103, -0.1919])
tensor([ 0.1039, -0.4565,  0.0605,  ...,  0.5889, -0.4781, -1.5301])
tensor([ 1.3591, -0.1410, -0.3595,  ...,  1.1604,  1.2490, -0.2488])
tensor([-0.1821,  0.0381,  0.1691,  ...,  1.0424,  1.2525, -1.2010])
tensor([-0.3701,  1.1267,  1.6215,  ...,  0.9781,  1.4080, -0.5670])
tensor([-0.2415,  0.0541, -0.3114,  ...,  0.2537, -0.2949,  0.0986])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.0495,  0.7729, -0.7797])
tensor([ 0.4271,  0.1026,  0.3017,  ..., -0.2192,  1.2059,  0.2509])
tensor([-0.0893, -0.4715, -0.7548,  ..., -0.3874,  1.9130, -0.5590])
tensor([-0.4412, -0.9116,  0.4660,  ...,  0.7231,  1.0878, -0.1878])
tensor([ 0.0434,  0.1392, -0.4155,  ..., -2.2781, -0.9842, -0.8171])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.2261, -0.1708, -0.2579])
tensor([-0.0623,  1.1052, -0.1352,  ...,  1.6196,  0.2126, -0.1868])
tensor([-0.0774, -0.3940, -0.3256,

tensor([-0.2053,  0.2502, -0.7327,  ..., -0.4341,  0.1708, -0.2841])
tensor([ 7.2008e-01,  2.3552e-01, -2.3989e-04,  ...,  2.8968e-01,
         1.4794e+00, -1.4140e+00])
tensor([-0.5423,  0.0268, -0.2013,  ...,  0.9124,  1.7303, -1.0152])
tensor([0.1131, 0.1575, 0.1414,  ..., 0.1662, 0.6187, 0.3036])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.1045,  0.2069, -0.8764])
tensor([-0.3252, -0.4169,  0.3226,  ..., -0.5232,  0.2941, -0.0987])
tensor([ 0.2210, -0.2911,  0.3106,  ...,  1.6541,  1.6955, -1.0435])
tensor([ 0.7099, -0.4779,  0.0939,  ...,  0.2354,  0.2434,  0.2262])
tensor([ 1.2369, -1.2607, -0.4261,  ...,  0.9797,  0.3033, -0.2469])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -1.8486,  1.0444, -0.4696])
tensor([-0.4502,  0.5195,  0.1148,  ...,  0.3875,  0.4570, -0.7563])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.0095,  0.3441, -0.5224])
tensor([-0.1881, -0.2484,  0.5997,  ..., -0.4356,  1.6331, -0.6439])
tensor([ 0.2678, -0.2839, -1.6761,  ...,  0.0458,  2.6724,  0.5413])
tensor([

tensor([ 0.0260,  0.0271,  0.7579,  ...,  0.7305, -0.3670, -0.9243])
tensor([-0.9187,  0.5547, -0.5026,  ..., -0.2354, -1.0852, -0.7231])
tensor([ 3.7346e-04,  2.3383e-01, -5.5994e-01,  ...,  6.2173e-01,
         7.1350e-01, -1.5085e-01])
tensor([-0.1821,  0.0381,  0.1691,  ...,  0.4405, -0.8735,  0.2582])
tensor([-1.6261, -0.4007,  0.5780,  ...,  1.2136, -0.8311, -1.4939])
tensor([-0.4078, -0.7021,  0.3506,  ...,  1.2488, -1.4081, -1.4521])
tensor([-0.8872, -0.2004, -1.0601,  ..., -0.6517, -1.0355, -0.0264])
tensor([-1.6261, -0.4007,  0.5780,  ...,  0.0415, -1.0180, -0.3873])
tensor([-0.4340, -0.7386,  1.0174,  ...,  0.9213, -0.7740, -1.0660])
tensor([ 0.1915,  0.2300, -0.2894,  ..., -1.7971, -1.0504,  0.8404])
tensor([ 0.1040,  0.1229, -0.0706,  ...,  0.0410,  0.2589,  0.2441])
tensor([-0.3040, -0.0634, -1.2906,  ..., -1.0214,  0.8555, -0.1483])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -2.2627, -0.6239,  0.4303])
tensor([-0.4340, -0.7386,  1.0174,  ...,  0.9827, -0.2206, -1.2113])
te

tensor([-0.3288,  0.2022, -0.5940,  ..., -0.9145, -0.6116, -0.3491])
tensor([ 0.4750, -0.3255,  0.9532,  ..., -0.9089,  2.6397,  0.3350])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -0.8594, -0.5147, -0.8906])
tensor([-0.0427, -0.2001,  0.2991,  ...,  0.9500,  1.5973, -0.9872])
tensor([-0.1589, -0.0327,  0.0890,  ..., -0.0137,  1.2954,  0.9327])
tensor([ 0.1915,  0.2300, -0.2894,  ..., -1.0857, -1.1285,  0.4397])
tensor([-0.1821,  0.0381,  0.1691,  ..., -0.0298, -0.4140, -0.5272])
tensor([ 0.1282,  0.1456, -0.2014,  ...,  0.3922, -1.2441, -1.2578])
tensor([-0.7026,  0.3013, -0.0241,  ...,  0.2045,  0.4699,  1.4475])
tensor([ 0.1040,  0.1229, -0.0706,  ..., -0.2300, -0.0784, -0.0386])
tensor([-0.3464,  0.2264, -0.0857,  ..., -1.1939,  1.2534, -0.2533])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -3.7342,  1.8487,  0.0195])
tensor([-0.3863,  0.6278, -0.0486,  ..., -0.4333,  0.2662,  0.3680])
tensor([ 0.1314,  0.3937, -0.5065,  ..., -0.1059, -0.6030,  0.0592])
tensor([-0.2569,  0.4148, -0.4112,

tensor([-0.3288,  0.2022, -0.5940,  ..., -0.5630, -0.6274,  0.8451])
tensor([ 0.1632, -0.5809,  0.4901,  ..., -0.6753,  0.9870,  1.3384])
tensor([ 0.1915,  0.2300, -0.2894,  ..., -1.9277, -0.3214,  0.7219])
tensor([-0.0925,  0.6733,  0.8286,  ..., -1.0969, -0.4731, -0.1956])
tensor([ 0.0434,  0.1392, -0.4155,  ..., -2.7097, -1.0605, -0.5842])
tensor([ 0.1040,  0.1229, -0.0706,  ..., -0.1400,  0.1610,  0.2441])
tensor([-0.3040, -0.0634, -1.2906,  ..., -0.6912,  1.5668,  0.1077])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -1.2409, -0.1653,  0.8433])
tensor([-0.4340, -0.7386,  1.0174,  ..., -0.0451,  0.6294, -0.9772])
tensor([-0.1094, -0.1722,  0.1200,  ..., -2.1162,  1.3810,  1.2389])
tensor([ 1.0734,  0.9579, -0.4632,  ..., -0.4419,  0.8588,  1.5106])
tensor([-0.2104, -0.4346, -0.4639,  ..., -1.6993, -0.3003, -0.1009])
tensor([-0.0248, -0.2016, -0.1380,  ..., -2.0567, -1.3156,  0.3996])
tensor([-0.3643,  0.0083, -0.9658,  ..., -0.4086, -0.6888,  0.2862])
tensor([-0.1821,  0.0381,  0.1691,

tensor([ 0.0098, -0.2075, -0.2807,  ..., -0.8305, -0.9096, -0.9549])
tensor([-0.4340, -0.7386,  1.0174,  ...,  1.0323, -0.8871, -1.6232])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.1626, -0.9717,  0.0386])
tensor([ 0.3003,  0.4550,  0.1821,  ..., -1.1880, -1.3837,  1.5879])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.6367, -0.5200,  0.2193])
tensor([ 0.1915,  0.2300, -0.2894,  ..., -1.5049, -0.3749,  0.1957])
tensor([ 0.3857, -0.3485, -0.5541,  ..., -0.3442, -0.2166, -0.1087])
tensor([-0.1947,  0.3419,  0.0669,  ..., -1.2428,  0.2187,  0.6042])
tensor([ 0.0786, -0.5134,  0.2467,  ..., -0.6575, -0.5773,  0.7399])
tensor([ 0.2499,  0.4410,  0.0523,  ..., -3.0635, -0.5198,  1.0423])
tensor([ 0.1040,  0.1229, -0.0706,  ..., -0.0816,  0.3344,  0.7199])
tensor([ 0.8477, -0.1967,  0.0180,  ...,  0.1466,  1.5620,  0.4779])
tensor([-0.3216, -0.2972, -0.3578,  ..., -0.5972, -0.0846,  0.5582])
tensor([-4.3721e-01,  5.5571e-04,  5.5110e-01,  ...,  1.9516e-01,
         1.0876e+00,  1.0676e+00])
te

tensor([ 0.0212, -0.1212,  0.3950,  ...,  0.1886,  0.8677,  0.5928])
tensor([ 0.1915,  0.2300, -0.2894,  ..., -1.1161,  1.0147,  2.0967])
tensor([ 0.1040,  0.1229, -0.0706,  ...,  0.1638,  1.0318, -0.1107])
tensor([ 0.2074, -0.5093,  1.2712,  ..., -0.1764,  1.4933,  0.3298])
tensor([-0.1115, -0.3943, -0.3937,  ..., -0.2167,  1.1916,  1.1848])
tensor([ 0.1849, -0.5320,  0.1351,  ..., -1.8406,  0.0564,  2.2285])
tensor([-0.1100,  0.3147,  0.5059,  ..., -0.5566,  1.4408,  0.5258])
tensor([ 0.1877, -0.2590, -0.2795,  ...,  0.0741,  1.9801,  0.9811])
tensor([-0.1713,  0.2059, -0.5061,  ...,  1.0446,  0.9810,  1.2576])
tensor([-0.2734,  0.7550, -0.0349,  ..., -0.3692,  0.3631,  0.4438])
tensor([-0.2569,  0.4148, -0.4112,  ..., -1.3952,  0.1705,  1.0811])
tensor([0.0792, 0.1019, 0.5308,  ..., 1.4853, 1.7728, 1.3791])
tensor([-0.8872, -0.2004, -1.0601,  ..., -0.1971,  0.9627,  1.1130])
tensor([ 0.0212, -0.1212,  0.3950,  ..., -0.1753,  0.4647,  0.7397])
tensor([ 0.2880, -0.1100, -0.3018,  ...,

tensor([ 0.0212, -0.1212,  0.3950,  ...,  0.2678,  0.6126,  0.5714])
tensor([ 0.1915,  0.2300, -0.2894,  ..., -0.9825,  0.9346,  2.1600])
tensor([ 0.1040,  0.1229, -0.0706,  ...,  0.1514,  0.9908, -0.1541])
tensor([ 0.2074, -0.5093,  1.2712,  ..., -0.2343,  1.4223,  0.3388])
tensor([-0.1115, -0.3943, -0.3937,  ..., -0.2397,  1.1719,  1.2908])
tensor([ 0.1849, -0.5320,  0.1351,  ..., -1.9010,  0.0752,  2.3855])
tensor([-0.1100,  0.3147,  0.5059,  ..., -0.6580,  1.3867,  0.6141])
tensor([ 0.1877, -0.2590, -0.2795,  ...,  0.0907,  1.8806,  1.0887])
tensor([-0.1713,  0.2059, -0.5061,  ...,  1.0500,  0.9191,  1.2123])
tensor([-0.2734,  0.7550, -0.0349,  ..., -0.2310,  0.2250,  0.4910])
tensor([-0.2569,  0.4148, -0.4112,  ..., -1.4876,  0.1346,  1.0887])
tensor([0.0792, 0.1019, 0.5308,  ..., 1.5011, 1.5909, 1.5658])
tensor([-0.8872, -0.2004, -1.0601,  ...,  0.0556,  0.6982,  1.1525])
tensor([ 0.0212, -0.1212,  0.3950,  ..., -0.2027, -0.1141,  0.5986])
tensor([ 0.2880, -0.1100, -0.3018,  ...,

tensor([-0.3288,  0.2022, -0.5940,  ..., -0.7137,  0.0304,  0.8614])
tensor([-0.1781,  0.7179, -0.5051,  ..., -0.4170,  2.9254,  0.8138])
tensor([ 0.4208,  0.4072, -0.0691,  ..., -1.0741,  0.2966,  2.0262])
tensor([ 0.1675, -0.9451, -0.2538,  ...,  1.7220,  0.1365, -0.3613])
tensor([ 0.1204, -0.0445,  0.1590,  ...,  0.8095,  1.0554, -0.5417])
tensor([-0.0312,  0.0804, -0.2824,  ..., -0.2648,  0.7183,  0.0665])
tensor([ 0.3178, -0.4187,  0.3023,  ...,  1.2824, -0.1634,  0.6368])
tensor([-0.3301, -0.4575, -0.1501,  ..., -0.0194,  0.6056,  1.2275])
tensor([-0.0690,  0.1126,  0.2371,  ...,  1.1359,  0.3974,  0.2680])
tensor([-0.2329,  0.4016,  0.4796,  ...,  1.7611,  1.4131, -0.2422])
tensor([0.1131, 0.1575, 0.1414,  ..., 0.9477, 1.1905, 1.0946])
tensor([-0.2543,  0.0933,  0.0835,  ...,  0.0848,  1.5498,  2.1165])
tensor([ 0.1083,  0.1691, -0.1745,  ...,  1.3137,  1.9235,  0.9001])
tensor([-0.1821,  0.0381,  0.1691,  ...,  1.7687,  0.6438,  1.9863])
tensor([-0.8108,  0.0316,  0.0742,  ...,

tensor([-0.1062, -0.1863, -0.7363,  ...,  0.0524,  0.1282,  0.8962])
tensor([-0.0427, -0.2001,  0.2991,  ..., -1.0062,  0.0855, -0.2271])
tensor([ 0.3506,  0.1588,  0.3250,  ..., -1.4894,  3.3350,  0.0901])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.0894,  0.1822, -0.0022])
tensor([ 0.1874, -0.2129, -0.0633,  ...,  1.4639,  0.6702, -0.0934])
tensor([ 0.1009, -0.5942, -0.8228,  ...,  0.5475, -0.9002, -0.3583])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -2.1733, -0.7915, -0.2692])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.7792,  0.0790, -0.7979])
tensor([ 1.1053, -0.1148, -0.2128,  ..., -0.3125,  0.1244,  1.1420])
tensor([ 0.0887, -0.0755,  0.2633,  ...,  0.6496,  0.8279,  1.4558])
tensor([ 0.1040,  0.1229, -0.0706,  ...,  0.7723,  0.6130, -0.4155])
tensor([-1.3581,  0.1988,  0.9673,  ...,  1.4855,  1.1145, -0.0149])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -2.2384,  0.2615,  1.3392])
tensor([-0.2564,  0.4552,  0.4011,  ...,  0.3606,  0.9422, -0.6243])
tensor([-0.4017, -0.0374, -0.5200,

tensor([-0.3288,  0.2022, -0.5940,  ...,  0.3388,  0.7663, -1.1312])
tensor([-0.3336, -0.1654, -0.1514,  ...,  1.0199,  1.8054, -0.7626])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -2.1079, -0.2401, -1.1026])
tensor([ 0.1874, -0.2129, -0.0633,  ...,  1.3865,  0.6282, -0.8926])
tensor([-0.6002, -0.0179,  0.2260,  ...,  0.2896,  0.3137, -0.7252])
tensor([ 0.1131,  0.1575,  0.1414,  ...,  0.5728, -0.3431,  0.1166])
tensor([-0.4269,  0.2657,  0.2653,  ...,  0.4556,  0.8586, -0.2680])
tensor([-0.8872, -0.2004, -1.0601,  ...,  0.0495,  0.6622, -0.3498])
tensor([-0.2471,  0.2483, -0.2670,  ...,  0.3166,  0.2254, -0.3841])
tensor([-0.2569,  0.4148, -0.4112,  ..., -1.4621, -0.1439, -0.9025])
tensor([-0.4807,  0.5334,  0.1476,  ...,  1.7849,  1.4764, -0.8906])
tensor([ 0.5228, -0.6651, -0.3625,  ...,  0.4045,  1.0296, -1.0077])
tensor([-0.8088,  0.6118,  0.5562,  ..., -0.5890,  1.3429, -2.3285])
tensor([-0.0248, -0.2016, -0.1380,  ...,  0.4546,  0.7332, -0.4000])
tensor([ 0.1071, -0.5934,  0.8992,

tensor([-0.3288,  0.2022, -0.5940,  ...,  0.1639,  0.0925, -0.3518])
tensor([ 0.4066,  1.0169,  0.2924,  ..., -0.2182,  1.4190,  1.0274])
tensor([-0.4755, -0.2662,  0.0437,  ..., -0.5928,  0.9516,  0.1309])
tensor([-0.3991, -0.6771, -0.1310,  ...,  1.7040,  3.0746,  0.0081])
tensor([ 0.5883, -0.3333,  0.6499,  ..., -0.5355,  0.5409, -0.0890])
tensor([-0.0690,  0.1126,  0.2371,  ...,  1.3234,  1.1445, -0.6120])
tensor([-0.3252, -0.4169,  0.3226,  ...,  0.1994,  1.3827,  0.6900])
tensor([ 0.2210, -0.2911,  0.3106,  ...,  0.9201,  1.5993,  0.4748])
tensor([-0.1821,  0.0381,  0.1691,  ..., -0.2377,  0.8593,  0.4435])
tensor([ 0.1330, -0.4108,  0.3018,  ...,  0.5192, -0.5544, -1.1559])
tensor([ 0.1131,  0.1575,  0.1414,  ...,  0.4017, -0.8876, -1.0906])
tensor([-0.2404, -0.2742, -0.2190,  ..., -1.4703, -1.6034,  1.1771])
tensor([ 0.3857, -0.3485, -0.5541,  ...,  0.0722, -0.9652,  0.6695])
tensor([-0.2568,  0.2002,  0.9871,  ..., -0.3155, -0.0175, -0.3461])
tensor([ 0.0999,  0.4622, -0.5532,

tensor([ 0.0007, -0.2541, -0.6276,  ..., -0.2716,  0.0124, -0.5610])
tensor([ 0.1851,  0.5494, -0.1737,  ..., -0.7744,  0.6725,  0.1563])
tensor([ 0.4516,  0.8299,  0.8129,  ..., -0.5226,  0.7233,  0.6316])
tensor([-0.2569,  0.4148, -0.4112,  ..., -1.2974, -1.0666, -0.6148])
tensor([-0.2404, -0.2309, -0.2505,  ...,  0.3726,  1.4772, -1.4224])
tensor([-0.1094, -0.1722,  0.1200,  ..., -2.0976,  1.3171,  0.0899])
tensor([ 0.1215,  0.7783,  0.2134,  ..., -0.8668,  1.5012,  0.4040])
tensor([-0.1821,  0.0381,  0.1691,  ..., -0.4916,  0.6672, -0.0199])
tensor([ 0.3495, -0.5691,  0.4441,  ...,  0.3882, -0.1157, -0.5367])
tensor([ 0.5049, -0.5347,  0.4722,  ...,  0.3160,  1.4255, -0.3986])
tensor([-0.8227, -0.4040,  1.0888,  ...,  0.7488,  1.3186, -0.8426])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -1.0042,  3.4437,  0.1666])
tensor([-0.9002, -0.4588,  0.1143,  ...,  0.9098,  2.1513, -0.2034])
tensor([ 0.0828, -0.1725, -0.7311,  ...,  0.8945,  1.0775, -0.0305])
tensor([-0.1821,  0.0381,  0.1691,

tensor([-0.5468, -0.2740, -0.5868,  ...,  0.7089, -0.1165, -1.6245])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -1.4045, -0.6778, -1.6977])
tensor([ 0.5029, -0.5492,  0.0919,  ...,  0.6386, -0.6066, -1.8337])
tensor([-0.9174,  0.0707,  1.3959,  ...,  1.1241, -1.6970, -0.9186])
tensor([-0.2569,  0.4148, -0.4112,  ..., -0.6198, -0.4790, -0.0264])
tensor([-0.4283, -1.3419, -0.2374,  ...,  0.9742,  1.0426, -0.7150])
tensor([-1.0932, -0.0060, -0.5022,  ...,  1.0446,  0.2534, -1.6535])
tensor([-0.8872, -0.2004, -1.0601,  ..., -0.8493, -0.6579, -0.0474])
tensor([-0.3288,  0.2022, -0.5940,  ..., -1.2513,  0.0299,  0.1287])
tensor([-0.1096,  0.2449,  0.5110,  ..., -0.1795, -1.0066, -0.1146])
tensor([-0.0312,  0.0804, -0.2824,  ..., -1.7434, -1.6386,  0.1871])
tensor([-0.0235, -0.4164, -0.5796,  ...,  0.8901, -1.0974, -0.6722])
tensor([ 0.0488, -0.1382,  0.3967,  ...,  0.6258, -0.6895, -1.0280])
tensor([-0.3216, -0.2972, -0.3578,  ..., -1.5139, -0.8592,  0.0438])
tensor([ 0.5029, -0.5492,  0.0919,

tensor([-0.2143,  0.3015, -0.9579,  ...,  0.0259,  0.3060, -0.4259])
tensor([-0.2782, -0.7782,  0.0304,  ..., -0.7098,  0.8630,  0.0922])
tensor([-0.8872, -0.2004, -1.0601,  ..., -0.7587,  0.5860, -0.9546])
tensor([ 0.5029, -0.5492,  0.0919,  ...,  0.2800,  1.0299, -1.2948])
tensor([-0.4030, -1.0271,  0.6708,  ...,  0.3658,  0.5251, -0.6574])
tensor([-0.4283, -1.3419, -0.2374,  ...,  0.4584,  0.3804, -0.5787])
tensor([-1.0932, -0.0060, -0.5022,  ..., -0.2039, -0.9458, -0.5018])
tensor([-0.0980,  0.2265,  0.1585,  ..., -0.3926,  0.9252,  0.5325])
tensor([-0.6390,  0.0332, -0.0143,  ...,  0.1071, -0.5590,  0.2559])
tensor([-0.5909, -0.3539,  0.1509,  ...,  0.2460,  1.2508,  0.0089])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -2.8149,  1.4133, -0.7010])
tensor([ 0.4171,  0.4411, -0.0274,  ...,  0.6647,  0.0907, -0.5674])
tensor([-0.0248, -0.2016, -0.1380,  ..., -1.2704,  0.4432, -0.6724])
tensor([-0.0312,  0.0804, -0.2824,  ..., -1.1251,  0.1770, -0.8828])
tensor([-0.0690,  0.1126,  0.2371,

tensor([-0.1035,  0.5138,  0.0170,  ..., -0.7207,  0.5280,  0.1931])
tensor([-0.0690,  0.1126,  0.2371,  ..., -0.5776,  0.9202, -1.0435])
tensor([ 0.0822,  0.3291, -0.0166,  ..., -0.9241,  0.9847,  0.9312])
tensor([ 1.0987,  0.8511, -0.4860,  ..., -0.7915,  1.6931,  0.2409])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.7608,  0.5538, -1.0516])
tensor([-0.4283, -1.3419, -0.2374,  ..., -0.0348,  0.7443,  0.1650])
tensor([-1.0932, -0.0060, -0.5022,  ..., -0.3543,  0.4818, -1.2579])
tensor([-0.0980,  0.2265,  0.1585,  ..., -1.3306,  3.1975,  0.9113])
tensor([-0.5478,  1.4106,  1.4413,  ..., -0.3705,  2.4000,  0.7645])
tensor([-0.2543,  0.0933,  0.0835,  ..., -0.6887,  1.3299,  0.3086])
tensor([ 4.7222e-04,  3.5108e-02, -5.7127e-01,  ...,  1.5863e+00,
         1.4112e+00, -9.5901e-01])
tensor([ 0.1040,  0.1229, -0.0706,  ...,  0.2670,  1.2583, -0.7201])
tensor([ 0.0758,  0.1008, -0.1360,  ..., -0.4249,  1.9156, -0.0846])
tensor([-0.8203, -0.9942,  0.4473,  ..., -1.7023,  1.7048,  0.7161])
te

tensor([-0.1929,  0.5692, -0.0141,  ...,  0.1371, -0.1821,  1.0430])
tensor([-0.0690,  0.1126,  0.2371,  ...,  1.1563,  1.0996, -0.7500])
tensor([0.2952, 0.5393, 0.3590,  ..., 0.9598, 1.7535, 0.1703])
tensor([-0.5445, -0.4760, -0.3032,  ...,  1.0414,  1.8042,  0.6115])
tensor([ 2.4783e-01, -2.4896e-01,  2.2195e-02,  ..., -2.5462e+00,
         1.8509e+00,  1.7701e-03])
tensor([-0.0690,  0.1126,  0.2371,  ...,  1.4967,  1.8303, -0.4312])
tensor([ 0.3611, -0.2598, -0.5600,  ...,  2.1840,  2.2080, -0.0568])
tensor([0.1131, 0.1575, 0.1414,  ..., 0.7667, 0.7951, 0.4281])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.2652,  0.3879, -0.1122])
tensor([-0.4223,  0.1452, -0.0869,  ...,  0.6990,  1.4506,  0.3144])
tensor([-0.4884,  0.3974,  0.5167,  ...,  0.5886,  1.3029,  1.0882])
tensor([-0.0690,  0.1126,  0.2371,  ...,  1.8098,  0.0354,  0.0616])
tensor([ 0.3611, -0.2598, -0.5600,  ...,  1.6662,  0.3732,  0.5548])
tensor([0.2789, 0.8781, 0.0917,  ..., 1.5712, 1.5854, 0.3780])
tensor([-0.5971,  0.

tensor([ 0.8640,  0.3556, -0.1532,  ...,  0.7044, -0.8952,  1.5402])
tensor([0.1131, 0.1575, 0.1414,  ..., 1.5303, 0.1978, 0.0167])
tensor([-1.1382,  0.2561,  0.4088,  ...,  1.6446,  1.2263, -0.9456])
tensor([ 0.3611, -0.2598, -0.5600,  ...,  2.2562,  0.2005, -0.0807])
tensor([-0.4262,  0.3978,  0.1398,  ...,  0.0025,  0.1119, -0.0648])
tensor([ 0.8475, -0.2688,  0.2739,  ...,  0.3307,  0.1417, -1.0324])
tensor([ 0.4495,  1.4651, -0.4098,  ..., -0.6722,  0.4438,  0.0524])
tensor([ 0.0328,  0.2275, -0.0274,  ..., -0.1194, -0.3680,  0.4444])
tensor([-0.8255, -0.0983,  0.4986,  ...,  0.4385, -0.3194, -0.2626])
tensor([ 0.1915,  0.2300, -0.2894,  ..., -0.1137,  1.0869,  0.6803])
tensor([ 0.1659,  1.6427, -0.4516,  ...,  0.5018,  0.0386, -0.4885])
tensor([-0.2569,  0.4148, -0.4112,  ..., -0.2637,  0.9167, -0.3181])
tensor([-0.0690,  0.1126,  0.2371,  ...,  1.5817,  1.5110, -0.6839])
tensor([ 0.3611, -0.2598, -0.5600,  ...,  2.4801,  1.7939,  0.0857])
tensor([-0.0248, -0.2016, -0.1380,  ...,

tensor([ 0.1688, -0.0987, -1.0669,  ..., -1.2116, -0.0155,  0.3573])
tensor([ 0.5430, -0.1905, -0.2897,  ..., -0.4954,  1.7741,  1.4464])
tensor([ 0.5194, -0.2690, -0.1756,  ..., -0.0437,  3.0204,  1.7001])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -1.5659, -1.4686,  0.9519])
tensor([-0.8262,  0.1177,  0.3139,  ...,  1.6451,  0.7714,  0.2352])
tensor([ 0.1915,  0.2300, -0.2894,  ...,  0.1712,  0.3814,  0.9447])
tensor([-0.0690,  0.1126,  0.2371,  ..., -0.1097, -0.1441,  0.7388])
tensor([ 0.2995,  0.3169, -0.1495,  ...,  0.7356,  0.9059,  0.7175])
tensor([-0.0062,  0.5871,  0.0844,  ...,  2.5112,  0.7405, -0.7499])
tensor([ 0.3611, -0.2598, -0.5600,  ...,  2.5457,  1.3300, -0.2452])
tensor([0.1131, 0.1575, 0.1414,  ..., 1.8018, 0.3961, 0.4360])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.3271,  0.6435,  0.6521])
tensor([ 0.6565, -0.2318, -0.1985,  ...,  0.7286,  0.5696,  0.1794])
tensor([ 0.0333,  0.3779,  0.0485,  ...,  0.9201,  0.6072, -0.0517])
tensor([ 0.3645, -0.1415, -0.0662,  ...,

tensor([-0.3288,  0.2022, -0.5940,  ..., -0.4883,  0.5547,  0.9948])
tensor([-0.5971,  0.5721,  0.7687,  ...,  0.5536,  1.9950,  1.1152])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.8713,  2.1233,  1.6684])
tensor([-0.5538,  0.3460,  0.1410,  ..., -0.2399,  2.7968,  2.0459])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.2893,  2.1156,  0.5821])
tensor([-0.0248, -0.2016, -0.1380,  ..., -0.7744,  2.8968,  0.6705])
tensor([-0.2595, -0.2168, -0.1721,  ...,  0.1539,  3.1748,  0.4247])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -2.2158,  3.2944, -0.1434])
tensor([ 0.3611, -0.2598, -0.5600,  ...,  1.8709,  2.1354,  0.4112])
tensor([-0.4262,  0.3978,  0.1398,  ...,  0.2384,  1.4746,  0.8878])
tensor([ 0.0847, -0.0261, -0.5010,  ...,  0.3279,  1.1017,  0.5634])
tensor([ 0.1120,  0.1016, -0.4143,  ...,  0.1073,  1.6711,  0.1075])
tensor([-0.5114,  0.2159, -0.1629,  ..., -0.4755,  1.2704, -0.1870])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.6160, -0.2764, -0.1868])
tensor([ 0.9355,  0.1041, -0.0584,

tensor([-2.8112e-02,  1.0824e+00, -1.2206e-01,  ..., -7.0956e-04,
         4.7232e-01,  6.8771e-01])
tensor([-0.2250,  0.4623,  0.2662,  ..., -0.1984,  1.9558, -0.4497])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -2.9288,  0.9383,  0.0983])
tensor([-0.2209, -0.8886, -1.0975,  ...,  0.6479,  0.5484, -0.2911])
tensor([-0.3138,  0.0934,  0.3244,  ...,  0.7833,  0.6981,  1.4858])
tensor([-1.3250, -0.2096,  0.1929,  ...,  1.2158,  1.4514,  1.1324])
tensor([-0.4262,  0.3978,  0.1398,  ..., -0.3323,  1.0382,  0.4899])
tensor([-0.1750,  0.4894,  0.8766,  ...,  0.0699,  0.4748,  0.4172])
tensor([-0.6715, -0.5156,  0.6701,  ..., -0.5021,  0.6137,  0.2257])
tensor([-0.7486, -0.0254,  0.9993,  ..., -0.0028,  0.7093,  0.1975])
tensor([-0.0202,  0.6020,  1.0735,  ...,  0.7233,  0.4365,  1.1546])
tensor([0.7203, 0.3430, 0.1828,  ..., 0.0308, 1.2784, 1.5231])
tensor([-0.1115, -0.3943, -0.3937,  ..., -1.0840,  0.9204,  1.3831])
tensor([ 0.1675, -0.9451, -0.2538,  ..., -1.2154,  1.2428,  0.8196])
tensor([

tensor([ 0.9823, -0.2517, -0.2941,  ...,  1.4181,  0.9276, -0.2969])
tensor([-0.3425,  0.0348,  0.1433,  ...,  1.2642,  1.0267, -0.9915])
tensor([-1.5240,  0.8472,  0.1693,  ...,  0.3665,  1.3934, -0.8343])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -1.9691, -1.0939,  0.8356])
tensor([ 0.1849, -0.5320,  0.1351,  ..., -2.1542, -0.4021,  1.3596])
tensor([-0.1596, -0.8633, -0.5642,  ..., -0.1348,  0.5654, -0.2954])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -1.0671, -0.1523,  0.4941])
tensor([ 0.1915,  0.2300, -0.2894,  ..., -2.0131, -0.7005,  1.6615])
tensor([ 0.1040,  0.1229, -0.0706,  ...,  0.0879,  0.7759, -0.2193])
tensor([-0.1265,  0.9066, -0.3927,  ..., -0.9849,  1.1016, -0.1949])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -1.5557,  1.1259,  0.8627])
tensor([ 0.1849, -0.5320,  0.1351,  ..., -3.9111, -0.7288,  1.9860])
tensor([-0.0042,  0.0414,  0.4427,  ..., -1.7726, -0.2475,  0.5523])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.3050, -0.4472,  1.2596])
tensor([ 0.7203,  0.3430,  0.1828,

tensor([-0.8302, -0.1902, -0.1608,  ...,  0.1235,  0.1341,  0.4679])
tensor([-2.1847e-04,  3.6538e-01, -9.4326e-01,  ..., -9.5378e-01,
        -1.1141e+00, -9.7820e-01])
tensor([-0.0248, -0.2016, -0.1380,  ..., -2.0031, -1.0465,  0.2338])
tensor([-0.1420, -0.2823, -0.4947,  ..., -0.5863, -0.9741, -1.7905])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.8956, -1.3608,  0.4737])
tensor([-0.9782, -0.4552,  0.1978,  ..., -0.0467,  0.2560, -0.2837])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.5384, -1.7193,  0.6671])
tensor([-0.7578, -0.2095,  0.1035,  ...,  0.2306,  0.6301,  0.7090])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -1.1234, -1.0305,  0.0719])
tensor([-0.0248, -0.2016, -0.1380,  ..., -1.7008, -1.0559,  0.7506])
tensor([ 0.9793,  0.4429, -0.3684,  ...,  1.3556,  0.0214, -0.6964])
tensor([-0.3425,  0.0348,  0.1433,  ...,  0.9225,  0.2856, -0.6032])
tensor([-1.5240,  0.8472,  0.1693,  ...,  0.3824,  0.3852,  0.3110])
tensor([-0.4368,  0.1378,  0.1467,  ..., -1.5861, -0.8605,  0.5260])
te

tensor([-0.3288,  0.2022, -0.5940,  ..., -0.8155, -0.0338,  0.6254])
tensor([0.4181, 0.4198, 0.1855,  ..., 0.3118, 0.3396, 0.2212])
tensor([-0.1732,  0.6795, -0.5541,  ...,  0.2708,  0.9677,  0.8445])
tensor([ 0.0060, -0.0758, -0.4209,  ..., -0.4626,  0.1917,  0.8911])
tensor([ 0.4001,  0.8245,  0.4364,  ..., -1.2610,  0.6021,  1.1350])
tensor([ 0.1875,  0.4185, -0.2568,  ..., -0.0367,  0.3752,  0.6001])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -3.8657,  0.4849,  0.0632])
tensor([-0.0770,  0.6666,  0.3972,  ...,  0.4614, -0.5437, -0.2332])
tensor([ 0.2468, -0.7389, -0.1596,  ...,  1.5501, -0.2630, -0.7282])
tensor([-0.7027, -0.1048, -0.1335,  ...,  1.0616,  0.8854,  0.5721])
tensor([-0.2789, -1.0366, -0.2256,  ...,  0.8984,  0.5935,  1.0020])
tensor([-0.1115, -0.3943, -0.3937,  ..., -1.2192,  0.0495,  0.8698])
tensor([0.1534, 0.0924, 0.6210,  ..., 0.2682, 1.0827, 0.1137])
tensor([-0.6382,  0.4469,  0.1693,  ...,  0.5870,  1.9150,  0.6569])
tensor([ 0.1877, -0.2590, -0.2795,  ..., -0.58

tensor([-0.0159, -0.0344, -0.0616,  ..., -0.1475, -0.5705, -0.6464])
tensor([-0.5584, -0.0403, -0.3713,  ...,  1.1243,  1.4546,  1.0019])
tensor([-0.1115, -0.3943, -0.3937,  ..., -1.3409,  0.0803,  0.7217])
tensor([-0.7104, -0.3234,  0.7747,  ...,  0.5435,  2.8620, -0.0665])
tensor([ 0.1877, -0.2590, -0.2795,  ..., -0.9109,  1.2084,  0.7992])
tensor([-8.8715e-01, -2.0040e-01, -1.0601e+00,  ..., -1.1250e+00,
        -8.7440e-05,  4.8974e-01])
tensor([ 0.0520,  0.3935,  0.0915,  ...,  0.7580, -0.2535, -0.3578])
tensor([ 0.6104, -0.6514,  0.7370,  ...,  0.2632,  0.7529, -0.9757])
tensor([ 0.1915,  0.2300, -0.2894,  ..., -1.4279,  0.5882,  0.5604])
tensor([-0.0690,  0.1126,  0.2371,  ..., -0.3460,  0.2219, -0.7245])
tensor([ 0.9793,  0.4429, -0.3684,  ...,  0.3597,  1.1752, -0.0497])
tensor([-0.5992,  0.3277,  0.0052,  ..., -0.9137,  1.7188, -0.6772])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -4.0898,  0.8102, -0.0499])
tensor([-0.6182,  0.3199,  0.4628,  ...,  0.3173,  1.1352, -0.2796])
te

tensor([ 0.8640,  0.3556, -0.1532,  ..., -0.4114, -0.0364,  0.8851])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.2213,  0.8126,  0.3034])
tensor([ 0.1040,  0.1229, -0.0706,  ..., -0.4224,  0.4126,  0.6350])
tensor([-0.1429,  0.1303, -0.4044,  ..., -0.5847,  1.8466,  2.1232])
tensor([ 0.0056, -0.4823, -0.0719,  ...,  0.0678,  3.6443,  1.4960])
tensor([ 0.0262, -0.3141,  0.0334,  ...,  1.4946,  0.6433,  0.6080])
tensor([ 0.2862, -0.3125, -0.3825,  ...,  0.2552,  1.3356,  0.6771])
tensor([-0.6587,  0.6728,  0.2602,  ...,  0.5804,  0.2957,  0.2184])
tensor([-0.8208,  0.1355, -0.7954,  ..., -0.2388,  1.6614,  0.0930])
tensor([-0.1821,  0.0381,  0.1691,  ...,  0.7364,  0.9178, -0.3041])
tensor([-0.5330,  0.0726, -0.0119,  ...,  0.6790,  0.6352, -0.4204])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.5457, -0.1153, -0.1526])
tensor([-0.6467,  0.2044,  0.8270,  ...,  0.6250,  1.2992,  0.8958])
tensor([-0.0063, -0.4363, -0.2163,  ...,  0.3094,  1.5368,  0.7014])
tensor([-0.1821,  0.0381,  0.1691,

tensor([-0.3288,  0.2022, -0.5940,  ..., -0.8742,  0.3181,  0.0323])
tensor([ 0.9355,  0.1041, -0.0584,  ..., -0.4286,  1.5993,  1.1657])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -2.8924, -0.1754,  0.1447])
tensor([-0.0690,  0.1126,  0.2371,  ..., -0.2077,  0.2251,  0.5382])
tensor([-0.6467,  0.2044,  0.8270,  ...,  0.2413,  1.3300,  1.6069])
tensor([-0.0063, -0.4363, -0.2163,  ...,  0.4927,  0.5206,  1.6299])
tensor([-0.6661, -0.1092,  0.3688,  ...,  0.3498,  1.1363,  0.9900])
tensor([-0.4815, -0.1207, -0.0397,  ..., -0.2751, -0.3545, -0.4554])
tensor([0.5394, 0.2146, 0.1039,  ..., 0.3602, 0.3038, 0.1060])
tensor([-0.0690,  0.1126,  0.2371,  ..., -0.8274, -0.3917, -0.5892])
tensor([ 0.9975,  0.2375, -0.0340,  ..., -2.3350,  0.6160,  0.3952])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -3.4216,  1.0873,  0.0384])
tensor([ 0.1040,  0.1229, -0.0706,  ..., -0.5898,  0.0719, -0.1274])
tensor([ 0.8074,  0.4433, -0.8406,  ..., -0.7662,  0.5120,  0.5055])
tensor([-0.1821,  0.0381,  0.1691,  ...,

tensor([ 0.1562, -0.3792,  0.3401,  ...,  0.8067,  0.1985,  2.3775])
tensor([ 0.1915,  0.2300, -0.2894,  ..., -0.0887,  1.7402,  3.2790])
tensor([ 0.3857, -0.3485, -0.5541,  ...,  0.6194, -0.4047,  1.1041])
tensor([ 0.2499,  0.4410,  0.0523,  ..., -0.7493, -0.5513,  1.6978])
tensor([ 1.3708, -0.7957, -0.0499,  ...,  0.2081,  0.8243,  0.2115])
tensor([-1.3162, -0.2737,  0.8110,  ...,  0.0852,  0.5127,  0.5608])
tensor([ 0.2499,  0.4410,  0.0523,  ..., -1.4270,  0.8456,  1.8252])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.1445,  0.1406,  1.0726])
tensor([0.1210, 0.3372, 0.2479,  ..., 0.6331, 0.3094, 1.4490])
tensor([-1.2691, -0.5098,  0.4404,  ...,  0.9262,  0.4979,  2.4319])
tensor([-0.1115, -0.3943, -0.3937,  ..., -0.3760,  0.2922,  3.4281])
tensor([-0.1725,  0.0560,  0.7486,  ...,  1.0220,  0.6875,  1.1005])
tensor([-0.0822,  0.8733,  0.1255,  ...,  0.9103,  1.0187,  1.7746])
tensor([ 0.1877, -0.2590, -0.2795,  ...,  0.9741,  1.2606,  2.6418])
tensor([ 0.1131,  0.1575,  0.1414,  ...,

tensor([ 0.1563, -0.3474, -0.2870,  ..., -0.7670,  0.1329,  0.3022])
tensor([ 0.7303, -0.1074,  0.5882,  ...,  0.8460,  1.2016,  1.2751])
tensor([ 0.1915,  0.2300, -0.2894,  ...,  0.2699,  1.0179,  1.2233])
tensor([ 0.3441,  0.3344,  0.1871,  ...,  1.9050, -0.0909, -0.0405])
tensor([ 0.3857, -0.3485, -0.5541,  ...,  2.4809,  0.3846, -0.5158])
tensor([ 0.0018, -0.6970,  0.1366,  ...,  0.5546, -0.0031, -0.4689])
tensor([-0.8872, -0.2004, -1.0601,  ..., -0.1489,  0.5754,  0.6290])
tensor([ 0.3513, -0.8462,  0.3155,  ...,  1.0584,  0.4800, -1.0932])
tensor([ 1.0980, -0.0044,  0.6513,  ..., -0.7702, -0.1673,  0.7989])
tensor([ 0.3857, -0.3485, -0.5541,  ..., -0.2979,  0.1336, -0.0840])
tensor([-0.6509,  1.4849,  0.0438,  ..., -0.1722, -0.3910, -0.3208])
tensor([-0.0690,  0.1126,  0.2371,  ..., -0.8300, -0.4806, -0.9227])
tensor([ 0.9975,  0.2375, -0.0340,  ..., -1.8541,  1.3340, -0.1357])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -3.2704,  1.1157, -1.0880])
tensor([ 0.1040,  0.1229, -0.0706,

tensor([-0.2069, -0.2854,  0.2875,  ...,  0.0204,  0.1850,  0.3740])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.6299, -0.0399,  1.5293])
tensor([-0.0623, -0.2736, -0.6689,  ..., -1.6145, -0.5468,  0.7359])
tensor([-0.0690,  0.1126,  0.2371,  ..., -1.2126, -0.7096, -0.4523])
tensor([ 0.0542,  0.0989,  0.0418,  ..., -1.8804,  1.4534,  1.0071])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -3.8674,  0.0673,  0.0487])
tensor([-0.0690,  0.1126,  0.2371,  ..., -0.0136,  0.4328,  0.1014])
tensor([ 0.0879, -0.2486,  0.0436,  ...,  0.1376,  1.0983,  1.0004])
tensor([-0.0063, -0.4363, -0.2163,  ...,  0.5175,  0.7096,  1.5346])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.9654, -0.2558,  1.0741])
tensor([ 0.5196,  0.8854,  0.4947,  ..., -0.3283,  0.0287,  1.6531])
tensor([ 0.0879, -0.2486,  0.0436,  ..., -0.3910,  0.4117,  1.4769])
tensor([-0.0248, -0.2016, -0.1380,  ..., -1.9926,  0.2013,  2.0613])
tensor([-0.8703, -1.1558,  0.4408,  ...,  0.2764,  0.0728,  1.2779])
tensor([-0.6316,  0.5915, -0.5277,

tensor([-0.8645, -0.8193,  0.7080,  ...,  0.4152,  0.6269,  0.6504])
tensor([ 0.1915,  0.2300, -0.2894,  ..., -1.2300,  0.2755,  1.4330])
tensor([ 0.0797,  0.1992, -0.0695,  ...,  0.6743,  0.7400, -0.0585])
tensor([-0.5878,  0.6401, -0.1525,  ...,  0.1985,  1.5743,  0.5692])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -3.1005, -0.5776,  0.0457])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.5051, -0.1938,  0.1611])
tensor([-0.9326,  1.0434,  1.1495,  ...,  1.6804, -0.7100,  1.0194])
tensor([-0.0248, -0.2016, -0.1380,  ..., -1.0696,  0.4401,  0.6179])
tensor([-0.4262,  0.3978,  0.1398,  ..., -0.7388,  0.0506,  0.2364])
tensor([ 0.6300,  0.1391,  0.0572,  ..., -0.5794, -0.0917,  0.2612])
tensor([ 0.6604,  0.5529, -0.2579,  ..., -0.5589,  0.1378,  0.8263])
tensor([ 0.4208,  0.4072, -0.0691,  ..., -0.9274, -0.3720,  1.5192])
tensor([-0.6405,  0.1717,  0.2913,  ...,  0.9795, -0.2988,  0.2640])
tensor([ 0.3078, -0.2273, -0.2031,  ...,  0.1608,  1.2991,  0.1163])
tensor([ 0.1305, -0.1077,  0.0960,

tensor([-0.2296, -0.0780, -0.7581,  ..., -0.4910, -0.2859,  2.2202])
tensor([-0.0690,  0.1126,  0.2371,  ..., -0.0603,  1.0670,  0.8246])
tensor([ 0.5765,  0.7233,  0.1832,  ..., -0.1512,  1.0633,  1.5935])
tensor([-0.1738, -0.0702,  0.5236,  ...,  0.5418,  0.0429,  1.9954])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.5131,  0.7082,  1.8661])
tensor([-0.5508,  0.5356, -0.6993,  ..., -0.2307,  0.3868,  0.5075])
tensor([ 0.3285, -0.3919, -0.1808,  ...,  1.4365, -0.1302,  1.9667])
tensor([-0.8872, -0.2004, -1.0601,  ..., -0.6140, -0.1437,  1.6966])
tensor([-0.2296, -0.0780, -0.7581,  ..., -0.8413, -0.8359,  1.9172])
tensor([ 0.0773,  0.1703,  0.5107,  ..., -0.8708,  0.2682,  1.8267])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -4.4918,  2.0777,  0.6353])
tensor([-0.5163,  0.0671,  0.4388,  ...,  0.3916,  1.1789,  1.8235])
tensor([ 0.2499,  0.4410,  0.0523,  ..., -1.7911,  0.4438,  1.4504])
tensor([ 0.0525, -0.5070,  0.3636,  ...,  0.8564,  0.2873,  1.2619])
tensor([ 0.1131,  0.1575,  0.1414,

tensor([ 0.0874,  0.1882,  0.4071,  ..., -0.1245,  0.1370,  1.3669])
tensor([ 0.3508,  0.4479,  0.3456,  ...,  0.2135, -0.8893, -0.3516])
tensor([ 0.2668, -0.8091, -0.6338,  ..., -2.1443, -0.8825,  0.5951])
tensor([ 0.2499,  0.4410,  0.0523,  ..., -1.9759,  0.0961,  1.3404])
tensor([ 0.3698, -0.4724, -0.4234,  ..., -0.2132, -0.2499,  3.0282])
tensor([-0.0248, -0.2016, -0.1380,  ..., -1.5959, -0.2352,  2.1945])
tensor([ 0.1732,  0.8133,  0.1114,  ...,  0.8833, -1.0366,  1.9403])
tensor([-0.0312,  0.0804, -0.2824,  ..., -0.3848, -0.3619,  0.8970])
tensor([-0.3936, -0.2725,  0.1204,  ...,  0.3629, -0.5722,  1.4685])
tensor([ 0.4208,  0.4072, -0.0691,  ..., -1.2226,  0.0064,  2.0628])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.2825, -0.1697,  0.8976])
tensor([ 0.1665,  0.0350, -0.0303,  ..., -0.2528, -0.5948,  2.0630])
tensor([-0.8323, -0.2564, -0.3113,  ...,  0.9510, -0.1486,  1.8580])
tensor([-0.8872, -0.2004, -1.0601,  ..., -0.1348, -0.0480,  1.0368])
tensor([-0.1177,  0.2633, -0.1671,

tensor([-0.2901,  0.3624, -0.5452,  ..., -0.5905, -0.3411,  1.4320])
tensor([0.1131, 0.1575, 0.1414,  ..., 0.3427, 0.2253, 1.3976])
tensor([ 0.3645, -0.1415, -0.0662,  ..., -0.9410,  0.2253,  1.0691])
tensor([-0.4262,  0.3978,  0.1398,  ...,  0.7263,  1.0331,  0.9767])
tensor([0.0218, 0.5739, 0.7175,  ..., 0.4981, 0.3377, 0.7792])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.8340, -0.7218,  1.1035])
tensor([-0.1736,  0.0736, -0.3008,  ...,  0.3013,  0.0214,  1.8501])
tensor([-1.3051,  0.5029, -0.7726,  ..., -0.5865, -0.7294,  2.3745])
tensor([-0.2543,  0.0933,  0.0835,  ..., -0.8040, -0.2998,  2.4617])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.8458, -0.1725,  1.2627])
tensor([-0.0770,  0.6666,  0.3972,  ..., -0.4477, -0.3808,  2.4671])
tensor([ 0.1366,  1.1099,  0.5916,  ..., -0.7664, -0.7274,  1.3373])
tensor([ 0.2478, -0.2490,  0.0222,  ..., -3.1873, -0.1343,  1.6398])
tensor([-0.0690,  0.1126,  0.2371,  ...,  1.2659,  0.3545,  1.2637])
tensor([ 0.3661, -0.7175,  0.9417,  ...,  0.51

tensor([-0.0159, -0.0344, -0.0616,  ...,  0.5229,  0.0698, -1.1816])
tensor([-0.0238, -0.0811,  0.1039,  ..., -0.0757,  0.6619, -1.5232])
tensor([-1.2289,  0.2348, -0.1960,  ...,  0.7100,  0.9683, -2.0780])
tensor([-0.8872, -0.2004, -1.0601,  ..., -0.5492,  0.2076, -0.4669])
tensor([-0.4350,  0.2461,  0.0982,  ..., -1.2296,  0.4448, -0.2637])
tensor([-0.4353,  0.2586,  0.3547,  ...,  1.0958,  2.5637, -1.1740])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.5042,  1.2363, -0.2382])
tensor([-0.0105, -0.5830,  0.2711,  ..., -0.4403, -0.0462, -0.8161])
tensor([-0.4959,  0.2016,  0.2681,  ...,  0.6225, -1.9498, -1.3209])
tensor([ 0.1131,  0.1575,  0.1414,  ...,  0.1852,  0.4948, -0.0816])
tensor([ 0.2313, -0.3767, -0.6084,  ..., -0.7144,  0.3791, -0.3429])
tensor([-0.0980,  0.2265,  0.1585,  ...,  0.0830,  1.4878, -0.8802])
tensor([-0.7524, -0.4685,  0.1846,  ...,  0.8982,  0.0936, -1.5773])
tensor([ 0.1979, -1.0170,  0.4579,  ...,  0.0027, -0.1816, -1.8269])
tensor([-0.4899, -0.0432,  0.1969,

tensor([ 0.1833,  0.1160, -0.1243,  ..., -0.4033, -1.1809,  0.0525])
tensor([-0.0105, -0.5830,  0.2711,  ..., -0.6324, -0.4206,  0.0884])
tensor([ 1.1961,  0.5340,  0.6493,  ..., -1.0153,  0.0580, -1.0055])
tensor([-0.2543,  0.0933,  0.0835,  ..., -2.3767, -0.9533,  0.3400])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.3021, -0.4895, -1.4550])
tensor([-0.5611,  0.5039,  0.3670,  ..., -0.6224, -1.1810, -0.9536])
tensor([-0.2587, -0.3169,  0.6655,  ...,  0.2003, -1.6287, -0.7251])
tensor([ 1.1177, -0.8388,  0.5548,  ..., -1.2865,  0.3421, -1.1394])
tensor([0.1131, 0.1575, 0.1414,  ..., 0.8547, 0.1704, 0.3480])
tensor([-0.4644, -0.9879,  0.4039,  ...,  0.4993,  0.8766, -0.4992])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.2588,  1.0095,  0.8296])
tensor([-0.3235,  0.1270,  0.2056,  ..., -0.0246,  0.0581, -0.3597])
tensor([-0.1115, -0.3943, -0.3937,  ..., -0.4339, -0.0466,  0.6164])
tensor([-0.0233, -0.0715, -0.8086,  ..., -0.4400,  1.1993,  0.5795])
tensor([-0.9187,  0.5547, -0.5026,  ...,

tensor([-0.0276, -0.4785, -0.6906,  ..., -0.0605,  0.0753,  0.8073])
tensor([ 0.6731, -0.2125,  0.3066,  ...,  1.1537,  1.6911, -0.2580])
tensor([ 0.1040,  0.1229, -0.0706,  ...,  1.8547,  1.1476, -0.5975])
tensor([ 0.9795,  0.2540, -1.0375,  ...,  0.0782,  1.3312, -0.1910])
tensor([ 0.2478, -0.2490,  0.0222,  ...,  3.0635, -1.2495, -0.2858])
tensor([ 1.6059, -0.3057, -0.3803,  ...,  1.8774,  0.5094,  0.4737])
tensor([ 1.2441,  0.2328, -0.0104,  ...,  1.0255,  0.0402, -0.6056])
tensor([-0.2569,  0.4148, -0.4112,  ..., -1.7184, -0.4583, -0.4209])
tensor([-0.3706,  0.5851,  0.2687,  ...,  0.8610,  1.2176,  0.0077])
tensor([-0.0979, -0.7214, -0.5683,  ...,  0.5734,  0.9835, -0.6847])
tensor([-0.0248, -0.2016, -0.1380,  ...,  0.8497,  0.1098, -0.4725])
tensor([ 0.4408, -0.8650,  0.4185,  ...,  1.8724,  0.9284, -1.0298])
tensor([-0.2379, -0.2091, -0.2344,  ...,  1.4266,  2.5727, -2.2658])
tensor([-0.2543,  0.0933,  0.0835,  ..., -1.2780,  0.1828,  0.1095])
tensor([-0.0690,  0.1126,  0.2371,

tensor([-0.0105, -0.5830,  0.2711,  ...,  0.4709, -0.4254,  0.0409])
tensor([-0.4959,  0.2016,  0.2681,  ...,  1.8740, -1.0130, -0.5823])
tensor([ 0.1915,  0.2300, -0.2894,  ...,  0.5149,  0.2934,  0.6817])
tensor([-0.1362,  0.7685, -0.4232,  ...,  0.4051, -0.5549, -0.2037])
tensor([-0.2569,  0.4148, -0.4112,  ..., -0.8821, -0.0417, -0.0718])
tensor([-0.0690,  0.1126,  0.2371,  ...,  0.3418,  1.9120, -0.3926])
tensor([ 0.0118, -0.9522,  0.5399,  ...,  0.8009,  1.8252,  0.3621])
tensor([ 0.1131,  0.1575,  0.1414,  ..., -0.0573,  2.5712,  0.6763])
tensor([ 0.2248, -0.7805,  1.2900,  ..., -0.1038,  1.7571,  0.3026])
tensor([0.1131, 0.1575, 0.1414,  ..., 0.1078, 2.8473, 1.6397])
tensor([0.4781, 0.0239, 0.3786,  ..., 0.0743, 2.1912, 0.7565])
tensor([-0.1052, -0.9387, -0.0376,  ...,  0.4522,  3.0771,  0.6239])
tensor([0.1131, 0.1575, 0.1414,  ..., 0.2567, 1.8569, 1.1424])
tensor([ 0.5007, -0.8363,  0.0597,  ..., -0.5585,  2.3980,  0.8011])
tensor([-0.1052, -0.9387, -0.0376,  ...,  0.3251,  2

In [120]:
from flair.embeddings import ELMoEmbeddings
from flair.data import Sentence
from tqdm import tqdm
import numpy as np


class Elmo(object):
    def __init__(self):
        # init embedding
        self.embedding = ELMoEmbeddings()

    def fit_transform(self, X):
        elmo_list = []
        for line in tqdm(X):
            dict_emb = {}
            sentence = Sentence(line)
            self.embedding.embed(sentence)
            for token in sentence:
                dict_emb[token] = token.embedding
            elmo_list.append(dict_emb)
        return np.array(elmo_list)


In [121]:
el = Elmo()
output = el.fit_transform(x)

100%|██████████| 100/100 [01:36<00:00,  1.04it/s]


In [124]:
output

array([{Token[0]: "The": tensor([-0.3288,  0.2022, -0.5940,  ..., -0.2876,  0.4907,  0.0943]), Token[1]: "presence": tensor([-0.4335,  1.0174, -0.7131,  ..., -0.3750,  1.4164, -0.4077]), Token[2]: "of": tensor([ 0.2478, -0.2490,  0.0222,  ..., -1.6505, -0.4505, -0.1460]), Token[3]: "communication": tensor([ 0.3358, -0.6698, -0.0683,  ...,  0.5426,  0.2742, -0.2719]), Token[4]: "amid": tensor([-5.6628e-01, -2.1065e-02,  2.1309e-06,  ..., -4.3520e-01,
                7.5123e-01, -5.5567e-01]), Token[5]: "scientific": tensor([-0.3897, -0.5744,  0.1275,  ...,  1.6141,  0.3421, -1.2750]), Token[6]: "minds": tensor([-0.4204, -0.1053, -0.7463,  ...,  1.6170,  1.7664, -0.2729]), Token[7]: "was": tensor([ 0.2981, -0.0738, -0.1319,  ...,  0.3482,  0.7202,  0.2195]), Token[8]: "equally": tensor([-0.1151, -0.6863, -0.0091,  ...,  0.2671,  0.0370, -1.0262]), Token[9]: "important": tensor([-0.4031, -0.2223, -0.0422,  ..., -0.1547,  0.9290, -1.7621]), Token[10]: "to": tensor([-0.1821,  0.0381,  0.169

In [108]:
!pip uninstall tensorflow -y
!pip uninstall tensorflow-cloud -y
!pip install -U tensorflow==1.15

Found existing installation: tensorflow 2.8.0
Uninstalling tensorflow-2.8.0:
  Successfully uninstalled tensorflow-2.8.0


ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\D073999\Documents\Priv-Dev\Retriever\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "C:\Users\D073999\Documents\Priv-Dev\Retriever\lib\site-packages\pip\_internal\commands\uninstall.py", line 89, in run
    uninstall_pathset.commit()
  File "C:\Users\D073999\Documents\Priv-Dev\Retriever\lib\site-packages\pip\_internal\req\req_uninstall.py", line 442, in commit
    self._moved_paths.commit()
  File "C:\Users\D073999\Documents\Priv-Dev\Retriever\lib\site-packages\pip\_internal\req\req_uninstall.py", line 282, in commit
    save_dir.cleanup()
  File "C:\Users\D073999\Documents\Priv-Dev\Retriever\lib\site-packages\pip\_internal\utils\temp_dir.py", line 184, in cleanup
    rmtree(self._path)
  File "C:\Users\D073999\Documents\Priv-Dev\Retriever\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 339, in wrapped_f
    return self(f, *args, **kw)
  

Looking in indexes: https://int.repositories.cloud.sap/artifactory/api/pypi/build-releases-pypi/simple, https://int.repositories.cloud.sap/artifactory/api/pypi/build-milestones-pypi/simple
  Using cached https://int.repositories.cloud.sap/artifactory/api/pypi/build-milestones-pypi/packages/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7553 sha256=2e79851a5a64d77ddea493df99b35153515a67e6f636e2315774d102362af3c8
  Stored in directory: c:\users\d073999\appdata\local\pip\cache\wheels\72\f2\b3\e50dc833b3e9829b60168ad4921ee7ccbfffe6738204b06a38
Successfully built gast
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Suc

You should consider upgrading via the 'C:\Users\D073999\Documents\Priv-Dev\Retriever\Scripts\python.exe -m pip install --upgrade pip' command.


In [109]:
!pip uninstall pytorch-lightning -y
!pip uninstall tensorflow-probability -y

In [154]:
##Tensorflow Hub ELMO-2
import tensorflow_hub as hub
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

elmo = hub.load("https://tfhub.dev/google/elmo/2").signatures["default"]

def create_elmo_embeddings(data):
    embed=elmo(
        tf.constant(data))["elmo"]
    with tf.compat.v1.Session() as sess:
        sess.run(tf.compat.v1.global_variables_initializer())
        sess.run(tf.compat.v1.tables_initializer())
        out_x=sess.run(embed)
        #out_y=ses.run(tf.reduce_mean(embed,1))
        return out_x
z=queries.Query.tolist()
elmo_input=z[:2]
elmo_output=create_elmo_embeddings(elmo_input)

In [228]:
x = collection.Passage[:40]

In [229]:
x

0     The presence of communication amid scientific ...
1     The Manhattan Project and its atomic bomb help...
2     Essay on The Manhattan Project - The Manhattan...
3     The Manhattan Project was the name for a proje...
4     versions of each volume as well as complementa...
5     The Manhattan Project. This once classified ph...
6     Nor will it attempt to substitute for the extr...
7     Manhattan Project. The Manhattan Project was a...
8     In June 1942, the United States Army Corps of ...
9     One of the main reasons Hanford was selected a...
10    group discussions, community boards or panels ...
11    punishment designed to repair the damage done ...
12    Tutorial: Introduction to Restorative Justice....
13    Organize volunteer community panels, boards, o...
14    The purpose of this paper is to point out a nu...
15    Each of these types of communities—the geogr...
16    The approach is based on a theory of justice t...
17    Inherent in many people’s understanding 

In [172]:
z=x.tolist()
elmo_input=z[:2]
elmo_output=create_elmo_embeddings(elmo_input)

In [187]:
def elmo_vectors(x):
  embeddings = []
  for elm in x:
        print(elm)
        e = elmo(elm.tolist())["elmo"]
        embeddings.append(elmo(x.tolist())["elmo"])

  with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.tables_initializer())
    # return average of ELMo features
    return sess.run(tf.reduce_mean(embeddings,1))

In [230]:
x = x.progress_apply(lambda text: np.array(
            stemming(
                removal(
                    tokenization(text)
                ))));x

100%|██████████| 40/40 [00:00<00:00, 367.86it/s]


0     [presenc, commun, amid, scientif, mind, equal,...
1     [manhattan, project, atom, bomb, help, bring, ...
2     [essay, manhattan, project, manhattan, project...
3     [manhattan, project, name, project, conduct, w...
4     [version, volum, well, complementari, websit, ...
5     [manhattan, project, classifi, photograph, fea...
6     [attempt, substitut, extraordinarili, rich, li...
7     [manhattan, project, manhattan, project, resea...
8     [june, 1942, unit, state, armi, corp, engineer...
9     [one, main, reason, hanford, select, site, man...
10    [group, discuss, commun, board, panel, third, ...
11    [punish, design, repair, damag, done, victim, ...
12    [tutori, introduct, restor, justic, restor, ju...
13    [organ, volunt, commun, panel, board, committe...
14    [purpos, paper, point, number, unresolv, issu,...
15    [type, communities—th, geograph, commun, vic...
16    [approach, base, theori, justic, consid, crime...
17    [inher, mani, people’, understand, notio

In [244]:
output = []
from nltk.tokenize.treebank import TreebankWordDetokenizer
output = []
for tokens in x:
    r =TreebankWordDetokenizer().detokenize(tokens)
    output.append(r)
output

['presenc commun amid scientif mind equal import success manhattan project scientif intellect cloud hang impress achiev atom research engin success truli meant hundr thousand innoc live obliter',
 'manhattan project atom bomb help bring end world war ii legaci peac use atom energi continu impact histori scienc',
 'essay manhattan project manhattan project manhattan project see make atom bomb possibl success project would forev chang world forev make known someth power manmad',
 'manhattan project name project conduct world war ii develop first atom bomb refer specif period project 194 â\x80¦ 21946 control us armi corp engin administr gener lesli r grove',
 'version volum well complementari websit first websiteâ\x80\x93th manhattan project interact historyâ\x80\x93i avail offic histori heritag resourc websit http wwwcfo doegovme70histori offic histori heritag resourc nation nuclear secur',
 'manhattan project classifi photograph featur first atom bomb â\x80\x94 weapon atom scientist nic

In [245]:
z=output#.tolist()
elmo_input=z[:2]
elmo_output=create_elmo_embeddings(elmo_input)

In [247]:
elmo_output

array([[[-0.16142987,  0.39164305,  0.2924859 , ..., -0.10307619,
          0.47838593,  0.10405383],
        [ 0.103149  , -0.20897631,  0.40901518, ..., -0.14926252,
          0.6624829 , -0.18022116],
        [-0.24741618,  0.30307624, -0.5055893 , ..., -0.26527908,
          0.17358826, -0.03860291],
        ...,
        [-0.12553898, -0.13239129, -0.04669396, ..., -0.32613608,
          0.5977138 ,  0.13836601],
        [ 0.5781988 , -0.35236633, -0.37354636, ..., -0.38017738,
          0.07846026,  0.09849334],
        [ 0.1008294 , -0.49969184, -0.3491489 , ...,  0.12266825,
          0.16703467,  0.42627513]],

       [[ 0.306329  ,  0.4091187 ,  0.48765004, ...,  0.13162018,
          0.62339723, -0.22805919],
        [ 0.7706266 , -0.03343945,  0.12615913, ...,  0.03431229,
          0.20650187, -0.33816066],
        [-0.01331159,  0.18552707, -0.15152037, ...,  0.21959701,
          0.87772703,  0.6102616 ],
        ...,
        [-0.02840841, -0.04353216,  0.04130162, ...,  

elmo_output